config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: :new
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :update
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end


end

private

def task_params
  params.require(:task).permit(:title, :details)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

<%= link_to "Back to list", index_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<br>
<div>
  <ul>
    <% @tasks.each do |task| %>
      <li>
      <%= task.completed %> <%= link_to task.title, task_path(task.id) %>
      <%= link_to "Delete", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
      </li>
    <% end %>
  </ul>

  <%= link_to "Create Task", new_path %>

</div>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

<%= link_to "Back to list", index_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>



<%= link_to "Back", index_path %>

<%= link_to "Edit", update_path %>